import enum
from sqlalchemy import Column, Integer, String, DateTime, Enum, Float
from sqlalchemy.sql import func
from database import Base


class UserRole(str, enum.Enum):
    admin = "admin"
    analyst = "analyst"
    persona = "persona"


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    role = Column(Enum(UserRole), default=UserRole.analyst, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Behavioral metadata captured at login - mirrors the same signal set
    # (device, IP, timestamp) the fraud model itself profiles. Useful later
    # if you want to demo "we practice what we detect."
    last_login_at = Column(DateTime(timezone=True), nullable=True)
    last_login_ip = Column(String, nullable=True)
    last_login_device = Column(String, nullable=True)


class Prediction(Base):
    """A logged /api/predict call - either submitted manually from the sandbox
    ("manual") or generated by replaying the persona's real historical
    transactions for the Live Monitor feed ("replay"). This is what makes
    Live Monitor "live": every prediction made anywhere in the app lands here."""
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True, nullable=False)
    source = Column(String, nullable=False, default="manual")

    transaction_amount = Column(Float, nullable=False)
    merchant_category = Column(String, nullable=False)
    merchant_id = Column(String, nullable=False)
    payment_method = Column(String, nullable=False)
    device_id = Column(String, nullable=False)
    device_type = Column(String, nullable=False)
    city = Column(String, nullable=False)
    hour_of_day = Column(Integer, nullable=False)
    distance_from_last_transaction_km = Column(Float, nullable=False)
    new_device = Column(Integer, nullable=False, default=0)
    new_location = Column(Integer, nullable=False, default=0)
    new_merchant = Column(Integer, nullable=False, default=0)

    prediction = Column(Integer, nullable=False)
    fraud_probability = Column(Float, nullable=False)
    top_features = Column(String, nullable=True)  # JSON-encoded list of {feature, shap_value}

    # Ground truth, only known for "replay" rows (the historical CSV's real label).
    # Manual sandbox rows are hypothetical scenarios with no ground truth, so this
    # stays null for them - used to compute a real false-positive rate on Analytics.
    true_label = Column(Integer, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
